# Site settings
title: gcinfo.org - Information about US Green Card process.
url: https://gcinfo.org
baseurl: /
permalink: pretty
exclude: [vendor]

# Build settings
markdown: CommonMarkGhPages
highlighter: rouge

plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Menu layout
nav:
  main:
    - name: Medical Interfiling
      path: /kb/medical-interfiling/
      sub: medical-interfiling
    - name: EAD/AP Renewal
      path: /kb/aos-eadap/renewal/
      sub: aos-eadap      
    - name: FAQ
      path: /kb/faq/gc-faq/
      sub: faq      
    - name: Useful Links
      path: /kb/useful-links/need-help/
      sub: useful-links
      
  second:
    - name: Create Page
      url: /kb/contribute/create-new-page/
      class: main-nav-link-separate
    - name: Github
      url: https://github.com/gcinfo-org/gcinfo.org

  footer:
    - name: Contact us
      url: https://forms.gle/6nNNpbWPT6iCjgM86
    - name: Disclaimer
      url: /kb/org/disclaimer/
    - name: Privacy Policy
      url: /kb/org/privacy-policy/
      
  medical-interfiling:
    - name: Interfiling
      path: /kb/medical-interfiling/
    - name: Medical Exam
      path: /kb/medical-interfiling/medical/     
    - name: Barcodes
      path: /kb/barcodes/      
    - name: Doctor's List
      path: https://docs.google.com/spreadsheets/d/163tiUMmWJ61gkK_P9KS6wc7c925IAsiXBJUK1nyouX8/edit?usp=sharing
    - name: Recommend Doctor
      path: https://forms.gle/jgKfqeYdCSistcFbA      
      
  barcodes:
    - name: Barcodes
      path: /kb/barcodes/
    - name: Custom Barcodes
      path: /kb/barcodes/custom-barcodes/
      
  aos-eadap:
    - name: Renewal
      path: /kb/aos-eadap/renewal/
    - name: AP Travel
      path: /kb/aos-eadap/ap-travel/
      
  faq: 
    - name: GC FAQ
      path: /kb/faq/gc-faq/
    - name: AP Travel FAQ
      path: /kb/aos-eadap/ap-travel/      
    - name: GC Acronyms
      path: /kb/faq/acronyms/
      
  useful-links:
    - name: GC Trackers
      path: /kb/useful-links/gc-trackers/
    - name: Ask Question
      path: /kb/useful-links/need-help/
    - name: Fee Calculator
      path: https://www.uscis.gov/feecalculator
     
  
